version: '3.8'

services:
  mytest:
    restart: always
    build: ./
#    image: openjdktest:2.0
    container_name: mytest
    volumes:
      - /root/docker-contains/mytest/logs-docker/:/bankend/logs/
      - /root/docker-contains/mytest/target/mytest.jar:/bankend/app.jar
    expose:
      - "8080"
    ports:
      - "8001:8080"
    networks:
      mytest:
        ipv4_address: 172.31.0.2
networks:
  mytest:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.31.0.0/16
          gateway: 172.31.0.1